name: Calculate Grade

on: push
jobs:
  grade:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    steps:
      - uses: actions/checkout@v4
      - run: pip install pyyaml
      - run: python .github/scripts/calculate_grade.py points.yml